app:
  inf:
    nims:
      # 관할관청기관코드 : 4050149 - 수지구보건소
      ofCd: 4050149
      # 기관명
      onm: 수지구보건소
      bssh-cd: TST000543
      url: https://test.nims.or.kr
      api-key: 998003699950fa950b798c9edea1b38f3cfbcf3b77e03e419
      api:
        bsshinfoStV1: /api/bsshinfo_st_v1.do
        productinfoKd: /api/productinfo_kd.do
        seqinfo: /api/seqinfo.do
        officeinfo: /api/officeinfo.do
        placeinfoV1: /api/placeinfo_v1.do
        reportinfo: /api/reportinfo_ggg.do
    mois:
      serverId: ADM405000069
    iros:
      url: https://apis.data.go.kr
      api-key: 0fTkYnZU6XjaAPAp6GzKW9Q6fYq8iaoSH9wKUZwz2PBjRXGM04aUgtO3a61xYGjL8nFZn4fjLGS9XErhMSXq%2Bw%3D%3D
      api:
        drugPrdtMcpnDtlInq: /1471000/DrugPrdtPrmsnInfoService05/getDrugPrdtMcpnDtlInq04
